Chemical:
  confidence: 0.85
  keywords:
  - cadmium
  - chemical
  - hazardous
  - lead
  - mercury
  - rohs
  priority: 1
  standards:
  - IEC 62321
  tests:
  - '% Ash Content'
  - '% Carbon Black Content'
  - '% Carbon Black Content by TGA'
  - '% Dose as Estimation of Noise Hearing Loss'
  - '% Extract (Volatile) Content'
  - '% Pigmentation in Base'
  - '% Solids'
  - '% Total Rubber HC Content(w/w) & (v/v)'
  - '% Volume change & % Masschange'
  - (Dry time hrs)Hard dry
  - (Dry time hrs)Surface dry
  - (Dry time hrs)track Free
  - (Drying Time)Hard Dry
  - (Drying time)Hard Dry
  - (Drying time)Hard dry
  - (Drying time)Surface dry
  - (Drying time)Tack free
  - (Drying time, hrs)Hard Dry
  - (Drying time, hrs)Surface Dry
  - (Flexibility adhesion )) Bendtest with 6.25 mm
  - (Flexibility adhesion )Scratchhardness
  - (Flexibility and adhesion )Bendtest with 6.25 mm diamanderal and type-1 Apparatus
  - (Flexibility and adhesion )Bendtest with 6.25mm
  - (Flexibility and adhesion )Bendtest with 6.5 mm
  - (Flexibility and adhesion)Bendtest with 6.25 mm
  - (Flexibility and adhesion)Scratch Hardness ( 1500 gm)
  - (Flexibility and adhesion)Scratch hardness (Load 1000g)
  - (Flexibility andadhesion)Scratch Hardness
  - (Free) Aniline
  - (Resistance to humidity under Condition of condensation)Resistance to humidity
EMC:
  confidence: 0.85
  keywords:
  - conducted
  - electromagnetic
  - emc
  - emi
  - emission
  - esd
  - immunity
  - radiated
  priority: 1
  standards:
  - CISPR
  - IEC 61000
  - IS 14700
  tests:
  - '% Ash Content'
  - '% Carbon Black Content'
  - '% Carbon Black Content by TGA'
  - '% Dose as Estimation of Noise Hearing Loss'
  - '% Extract (Volatile) Content'
  - '% Pigmentation in Base'
  - '% Solids'
  - '% Total Rubber HC Content(w/w) & (v/v)'
  - '% Volume change & % Masschange'
  - (Dry time hrs)Hard dry
  - (Dry time hrs)Surface dry
  - (Dry time hrs)track Free
  - (Drying Time)Hard Dry
  - (Drying time)Hard Dry
  - (Drying time)Hard dry
  - (Drying time)Surface dry
  - (Drying time)Tack free
  - (Drying time, hrs)Hard Dry
  - (Drying time, hrs)Surface Dry
  - (Flexibility adhesion )) Bendtest with 6.25 mm
  - (Flexibility adhesion )Scratchhardness
  - (Flexibility and adhesion )Bendtest with 6.25 mm diamanderal and type-1 Apparatus
  - (Flexibility and adhesion )Bendtest with 6.25mm
  - (Flexibility and adhesion )Bendtest with 6.5 mm
  - (Flexibility and adhesion)Bendtest with 6.25 mm
  - (Flexibility and adhesion)Scratch Hardness ( 1500 gm)
  - (Flexibility and adhesion)Scratch hardness (Load 1000g)
  - (Flexibility andadhesion)Scratch Hardness
  - (Free) Aniline
  - (Resistance to humidity under Condition of condensation)Resistance to humidity
Electrical:
  confidence: 0.85
  keywords:
  - current
  - dielectric
  - electric
  - electrical
  - insulation
  - power
  - resistance
  - strength
  - voltage
  priority: 1
  standards:
  - IEC 60068
  - IEC 60529
  - IEC 60947
  - IEC 62271
  - IS 302
  tests:
  - ' Damage limit proof testand test of tightness ofthe interface betweenend ttings
    & Insulatorhousing a] Visualexamination b]Verication of dimensionsc] Mechanical
    routine testd] Performance of thetest'
  - ' Determination oftransient Voltage transfercharacteristics/ Transfer Surge Voltagemeasurement'
  - ' Elongation test'
  - ' Torsion Resistance of Unused Lamps'
  - '% Elongation'
  - '% Elongation at break for Insulation(IE5) and Sheath(SE1 & SE5)'
  - '% Elongation of insulation &sheath before ageing'
  - '% Elongation of round/formed steel wire'
  - '% of Elongation'
  - ( Chlorine & Bromine Content ) Determinationof halogen content
  - ( Conductivity Test )Determination of halogencontent
  - '( Halogen : Fluorine )Determination of halogencontent'
  - ( Leakage Current Test &Dielectric Strenght Testafter Spillage , Overow,Cleaning
    & Ingress of Protection Test)
  - ( p H Test ) Determinationof halogen content
  - (5.1)General
  - (5.2) Insulation and wiring
  - (5.3) Venting
  - (A) Test on Conductor- Tensiletest (For Aluminium)
  - (A) Test on Conductor-Annealing Test (For Copper)
  - (A) Test on Conductor-Conductor Resistance Test
  - (A) Test on Conductor-Persulphate test (For Tinned Copper Conductor cable Only)
  - (A) Test on Conductor-Wrapping Test (For Aluminium)
  - (A) Tests on Conductor Annealing Test (For Copper)
  - (A) Tests on Conductor Tensile Test (For Aluminiumm)
  - (A) Tests on Conductor Wrapping Test (For Aluminium)
  - (A) Tests on Conductor-Conductor Resistance Test
  - (A)Tests on Conductor Conductor Resistance Test
  - (A)Tests on Conductor Tensile Test (For Aluminium)
  - (A)Tests on Conductor Wrapping Test (For Aluminium)
  - (A)Tests on Conductor-Annealing Test (For Copper)
Environmental:
  confidence: 0.85
  keywords:
  - cold
  - damp
  - environmental
  - heat
  - humidity
  - ip
  - protection
  - salt
  - spray
  - temperature
  priority: 1
  standards:
  - IEC 60068
  tests:
  - (Dry Heat Cycle)High Temperature chamber size:L-70 Inch, W-47 Inch, H-37 Inch
  - (Dry Heat Test for Heat Dissipating Items with Gradual change of Temperature)
  - (Dry Heat Test for Heat Dissipating Items withsudden change of Temperature)
  - (Dry Heat Test for Non-Heat Dissipating Itemswith Gradual change of Temperature)
  - (Dry Heat Test for Non-Heat Dissipating Itemswith sudden change of Temperature)
  - (IK01 IK02 IK03 IK04 Ik 05 IK06 IK07 IK08 ) -Pendulum length -Hammer Weight
  - (IK01 IK02 IK03 IK04 Ik 05 IK06 IK07 IK08 IK09 IK10)- Pendulum length -Hammer
    Weight
  - ',"Test VI Commercialvehicle, engine, gearbox Sinusoidal vibration'
  - 1 P-X4
  - 1st characteristic numeral 1
  - 1st characteristic numeral 2
  - 1st characteristic numeral 3
  - 1st characteristic numeral 4
  - 1st characteristic numeral 5
  - 1st characteristic numeral 6
  - 1st characteristic numeral IP1 X to IP6 X
  - 2nd characteristicnumeral 1
  - 2nd characteristicnumeral 2
  - 2nd characteristicnumeral 3
  - 2nd characteristicnumeral 4
  - 2nd characteristicnumeral 5
  - 2nd characteristicnumeral 6
  - 2nd characteristicnumeral 7
  - 2nd characteristicnumeral 8
  - 2nd characteristicnumeral IPX1 to IPX9,Drip proof
  - 7 J Impact test for polymericenclosures / Impact test
  - :Sealing (Gas tightness)/ High Altitude Test
  - AC Current Measurement
  - AC POWER FREQUENCYVOLTAGE TEST
  - AC Voltage Measurement
High_Voltage:
  confidence: 0.85
  keywords:
  - discharge
  - high
  - hv
  - impulse
  - lightning
  - partial
  - voltage
  priority: 1
  standards:
  - IEC 60060
  - IEC 60137
  - IEC 60168
  - IEC 62271
  tests:
  - ' Determination oftransient Voltage transfercharacteristics/ Transfer Surge Voltagemeasurement'
  - ( Sound Test) Noise Test
  - 1. Cooling Overload Test , 2.Cooling Low , Temperature Test and Freezing Draft
    Interference Test , 3.Condensate Treatment and Exposure Test
  - 1. Maximum Cooling Performance Test , 2. Minimum Cooling, Freeze-up Air Blockage
    & Freeze-up Drip Performance Test,3.Condensate Control and Enclosure Sweat Performance
    Test
  - 1. Maximum Operating Condition Test (Cooling) ,2.Freeze-up Test , 3.Evaporator
    Air Blockage Test , 4. Enclosure Sweat Test , 5.Condensate Disposal Test , 6.
    Maximum Operating , Condition Test(Heating)
  - 1. Maximum Operating Condition Test , 2. Freeze-up Test , 3. Enclosure Sweat Test,4.Condensate
    Disposal Test, 5.Noise Test
  - 4 Rating capacity test(Cl.4 )
  - AC voltage withstand test.
  - AUTOMATIC DEFROSTTEST
  - Abnormal Operation
  - Acceptance test (Cl.16.4)
  - Acceptance test Cl.12.4 Performance Test(Cl.12.4.1) Pressure Test or Leakage Test(Cl.
    12.4.2)Leakage Current Test (Cl.14.4.3)
  - Active Mode
  - Air Blockage Test
  - Air Filter
  - Air Flow Measurement
  - Air ow Measurement
  - Air ow measurement
  - Ambient Temperature
  - Annual Energy Consumption
  - Annual Energy Consumption (AEC)
  - Annual Energy Consumption (Cl.8 )
  - Annual Energy Consumption(AEC)
  - Annual energyconsumption
  - Appliances with Integral Pumps
  - Application Rating
  - Application Ratings
  - Application Ratings -Cooling Capacity
  - Applied voltage test
  - Applied voltage test (Dry Power Frequency Voltage Withstand Test)
Mechanical:
  confidence: 0.85
  keywords:
  - endurance
  - measurement
  - mechanical
  - operation
  - resistance
  priority: 1
  standards:
  - IEC 62271
  tests:
  - ' Resistance To External Blow At 0 C'
  - '% Ash Content'
  - '% Compression Set'
  - '% Elongation'
  - '% Elongation Test'
  - '% Elongation after fracture'
  - '% Elongation at Yield and atbreak'
  - '% Elongation at break'
  - '% Elongation atmaximum force'
  - '% Elongation of strand'
  - '% Elongation on 600 mm Gauge Length'
  - '% Elongation test'
  - '% Reduction Area'
  - '% Reduction in Area'
  - '% Reduction of Area'
  - '% Reduction of area'
  - '% Reduction of area afterfracture'
  - '% Tension Set'
  - '% Total Elongation at Maximum Force'
  - '% Total Elongation at gaugelength 600 mm'
  - '% Total Elongation at gaugelength 600mm'
  - '% elongation'
  - '% of Elongation'
  - '% of elongation Cl no 10 of IS2062:2011'
  - '% of elongation Cl no 13 of IS2002:2024'
  - '% of elongation Cl no 13 of IS6419'
  - '% of elongation Cl no 7, 7.2 of IS 617:2024'
  - '% of elongation Cl no 9.2 of IS1786:2008'
  - '%Elongation'
  - '%RA'
Safety:
  confidence: 0.85
  keywords:
  - earthing
  - electric
  - fire
  - flame
  - leakage
  - safety
  - strength
  priority: 1
  standards:
  - IEC 60695
  - IS 302
  tests:
  - (Glowing/hot-wire basedtest methods - Glow-wireappartus and cpommontest procedure)
    - Commontest procedure
  - (Provision For Earthing
  - 1008 Hour Current Cycling
  - 1008 h Current Cycling
  - 1008 h Current cycling
  - 1008 hour Current cycling
  - 1st Characteristic Numeral IP1 X to IP6 X
  - 25 % Drain time test using 2 GPM nozzle
  - 25 % Drainage Time
  - 25 % Drainage test
  - 25% & 50 % Drainage time offoam conc. after temperaturecondition
  - 25% & 50% Drainage time offoam before temperaturecondition
  - 25% Drain Time
  - 25% Drain Time Test
  - 25% Drainage Time
  - 25% Drainage Time test
  - 25% Drainage time
  - 25% Reignition Time(Burn Back Resistance Period)
  - 2nd Characteristic Numeral IPX1 to IPX6
  - 3 ply construction cookerbody
  - 30 - day leakage test
  - 30 m A touch current type testfor isolated inverters
  - 50 W (HB/V Class)
  - 50 W horizontal andvertical ame testmethods
  - 500 W (5 V Class)
  - 500 W ame test method
  - A.C. Voltage Test
  - ABNORMAL OPERATION
  - ABNORMAL OPERATION(Clause no. 19.2, 19.3,19.4, 19.5, 19.6, 19.7,19.8, 19.10, 19.11.1,19.11.2,
    19.11.3, 19.12,19.13)
  - AC & DC voltage test
Thermal:
  confidence: 0.85
  keywords:
  - cold
  - heat
  - rise
  - temperature
  - thermal
  priority: 1
  standards:
  - IEC 60068
  tests:
  - Accelerated ageing andheat resistance tests
  - Ageing at -40 degree C
  - Aging - dry and damp heattests
  - Bump Test/ Roadability
  - Burning Behavior
  - Burning behavior/Flammability
  - Climatic Ageing
  - Cold Test/Lowtemperature test
  - Combined climatic(temperature/humidity)and dynamic test
  - Compositetemperature/Humiditycyclic test
  - Conventional Index of Toxicity (CIT)
  - Damp heat /Steady state
  - Damp heat, steady state
  - Drop Test
  - Dry Heat / High Temperature
  - Environmental Cycle Resistance Test (+80/-40)C
  - Environmental Test-Test A:Cold
  - Environmental Testing-Test B:Dry
  - 'Environmental Testing-Test Db: Damp heat,cyclic'
  - Environmental Testing-Whisker test methods forcomponents and partsused in electronicassemblies
  - 'Environmental testing-Test Z/AD: Compositetemperature/Humidity Cyclic Test'
  - 'Environmental testing-Tests: Damp heat, Steady State'
  - Evironmental testing -Rapid change oftemperature/ Change oftemperature withspecied
    rate of change
  - Fire Hazard Testing
  - Flammability test
  - Heat Ageing test
  - Heat Release Rate
  - Heat Resistance Test
  - Heat ageing Resistance
  - Heat cycle resistance test
